sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

env:
  global:
    - BLINKHASH_UTXO_LIB_TEST_SKIP_3PBP=1
  jobs:
    - TEST_SUITE=standard
    - TEST_SUITE=coverage

matrix:
  include:
    - node_js: "7"
      env: TEST_SUITE=standard
    - node_js: "7"
      env: TEST_SUITE=coverage

install: npm install && npm install -g codecov
script:
  - npm run-script $TEST_SUITE
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
