language: node_js
node_js:
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
os: "linux"
dist: "xenial"
env:
  global:
    - BLINKHASH_UTXO_LIB_TEST_SKIP_3PBP=1
  jobs:
    - TEST_SUITE=standard
    - TEST_SUITE=coverage
jobs:
  include:
    - stage: test
      install: npm install
      script: npm run-script $TEST_SUITE
    - stage: coverage
      node_js: 12.16
      install: npm install && npm install -g codecov
      script:
        - npm run-script coverage
        - npm run coverage-report
        - codecov
